begin;

alter table public.profiles
  add column if not exists is_admin boolean not null default false;

create table if not exists public.app_error_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  severity text not null default 'error' check (severity in ('error', 'warning', 'info')),
  source text not null default 'client',
  message text not null,
  route text,
  details jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists app_error_logs_created_at_idx on public.app_error_logs (created_at desc);
create index if not exists app_error_logs_user_id_idx on public.app_error_logs (user_id);

alter table public.app_error_logs enable row level security;

grant select, insert on public.app_error_logs to authenticated;
grant usage, select on sequence public.app_error_logs_id_seq to authenticated;

create policy app_error_logs_insert_own
on public.app_error_logs for insert to authenticated
with check (user_id = (select auth.uid()));

create policy app_error_logs_select_admin
on public.app_error_logs for select to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = (select auth.uid())
      and profiles.is_admin = true
  )
);

commit;
